# Copyright 2026 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[workspace]
members = ["hawkeye", "xtask"]
resolver = "3"

[workspace.package]
edition = "2024"
homepage = "https://github.com/fast/hawkeye"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/fast/hawkeye"
rust-version = "1.89.0"

[workspace.dependencies]
# Workspace dependencies
hawkeye = { version = "7.1.0", path = "hawkeye" }

# crates.io dependencies
clap = { version = "4.6.6", features = ["derive"] }
exn = { version = "0.3.1" }
gix = { version = "0.87.1", default-features = false, features = [
  "max-performance-safe",
  "revision",
  "sha1",
  "sha256",
  "status",
] }
ignore = { version = "0.4.33" }
jiff = { version = "0.2.35", default-features = false, features = ["std"] }
log = { version = "0.4.34", features = ["kv_serde", "serde"] }
logforth = { version = "0.30.1", features = ["starter-log"] }
minijinja = { version = "2.24.0" }
same-file = { version = "1.0.6" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
tempfile = { version = "3.27.0" }
toml = { version = "1.1.4" }
which = { version = "8.0.6" }

[workspace.lints.rust]
unknown_lints = "deny"
unsafe_code = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
too_many_arguments = "allow"
type_complexity = "allow"

[workspace.metadata.release]
pre-release-commit-message = "chore: release v{{version}}"
shared-version = true
sign-tag = true
tag-name = "v{{version}}"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
