[package]
name = "native"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.76.0"

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
git2 = "0.18.3"
jni = "0.21.1"
snafu = "0.8.2"
