# Copyright 2024 tison <wander4096@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2024 - 2024, tison <wander4096@gmail.com> and the HawkEye contributors
# SPDX-License-Identifier: Apache-2.0

[SHARPSTAR_STYLE]
firstLine = '#*'
endLine = ' *#'
beforeEachLine = ' * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*#\*.*$'
lastLineDetectionPattern = '.*\*#(\s|\t)*$'

[PERCENT_STYLE]
firstLine = ''
endLine = "\n"
beforeEachLine = '% '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '^% .*$'
lastLineDetectionPattern = '^% .*$'

[BRACESSTAR_STYLE]
firstLine = '{*'
endLine = ' *}'
beforeEachLine = ' * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*\{\*.*$'
lastLineDetectionPattern = '.*\*\}(\s|\t)*$'

[EXCLAMATION_STYLE]
firstLine = '!'
endLine = "!\n"
beforeEachLine = '! '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '!.*$'
lastLineDetectionPattern = '!.*$'

[MVEL_STYLE]
firstLine = '@comment{'
endLine = '}'
beforeEachLine = '  '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
firstLineDetectionPattern = '@comment\{$'
lastLineDetectionPattern = '\}$'

[APOSTROPHE_STYLE]
firstLine = "'"
endLine = "'\n"
beforeEachLine = "' "
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = "'.*$"
lastLineDetectionPattern = "'.*$"

[TRIPLESLASH_STYLE]
firstLine = '///'
endLine = "///\n"
beforeEachLine = '/// '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '///.*$'
lastLineDetectionPattern = '///.*$'

[PHP]
firstLine = '/*'
endLine = ' */'
beforeEachLine = ' * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
skipLinePattern = '^<\?php.*$'
firstLineDetectionPattern = '(\s|\t)*/\*.*$'
lastLineDetectionPattern = '.*\*/(\s|\t)*$'

[LUA]
firstLine = "--[[\n"
endLine = "\n]]"
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
firstLineDetectionPattern = '--\[\[$'
lastLineDetectionPattern = '\]\]$'

[SCALA_STYLE]
firstLine = '/**'
endLine = '  */'
beforeEachLine = '  * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*/\*.*$'
lastLineDetectionPattern = '.*\*/(\s|\t)*$'

[BATCH]
firstLine = '@REM'
endLine = "@REM\n"
beforeEachLine = '@REM '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '@REM.*$'
lastLineDetectionPattern = '@REM.*$'

[MUSTACHE_STYLE]
firstLine = '{{!'
endLine = '}}'
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '\{\{\!.*$'
lastLineDetectionPattern = '\}\}.*$'

[HAML_STYLE]
firstLine = '-#'
endLine = "-#\n"
beforeEachLine = '-# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^-#!.*$'
firstLineDetectionPattern = '-#.*$'
lastLineDetectionPattern = '-#.*$'

[PERCENT3_STYLE]
firstLine = '%%%'
endLine = "%%%\n"
beforeEachLine = '%%% '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '%%%.*$'
lastLineDetectionPattern = '%%%.*$'

[EXCLAMATION3_STYLE]
firstLine = '!!!'
endLine = "!!!\n"
beforeEachLine = '!!! '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '!!!.*$'
lastLineDetectionPattern = '!!!.*$'

[ASP]
firstLine = '<%'
endLine = '%>'
beforeEachLine = "' "
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*<%( .*)?$'
lastLineDetectionPattern = '.*%>(\s|\t)*$'

[SCRIPT_STYLE]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[JAVAPKG_STYLE]
firstLine = "\n/*-"
endLine = ' */'
beforeEachLine = ' * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
skipLinePattern = '^package [a-z_]+(\.[a-z_][a-z0-9_]*)*;$'
firstLineDetectionPattern = '(\s|\t)*/\*.*$'
lastLineDetectionPattern = '.*\*/(\s|\t)*$'

[DOUBLESLASH_STYLE]
firstLine = ''
endLine = "\n"
beforeEachLine = '// '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '//.*$'
lastLineDetectionPattern = '//.*$'

[XML_STYLE]
firstLine = "<!--\n"
endLine = "\n-->"
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
skipLinePattern = '^<\?xml.*>$'
firstLineDetectionPattern = '(\s|\t)*<!--.*$'
lastLineDetectionPattern = '.*-->(\s|\t)*$'

[ASCIIDOC_STYLE]
firstLine = '////'
endLine = "////\n"
beforeEachLine = '  // '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '^////$'
lastLineDetectionPattern = '^////$'

[SEMICOLON_STYLE]
firstLine = ';'
endLine = ";\n"
beforeEachLine = '; '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = ';.*$'
lastLineDetectionPattern = ';.*$'

[DOUBLETILDE_STYLE]
firstLine = '~~'
endLine = "~~\n"
beforeEachLine = '~~ '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '~~.*$'
lastLineDetectionPattern = '~~.*$'

[SLASHSTAR_STYLE]
firstLine = '/*'
endLine = " */\n"
beforeEachLine = ' * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*/\*.*$'
lastLineDetectionPattern = '.*\*/(\s|\t)*$'

[FTL_ALT]
firstLine = "[#--\n"
endLine = "\n--]"
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
skipLinePattern = '\[#ftl(\s.*)?\]'
firstLineDetectionPattern = '(\s|\t)*\[#--.*$'
lastLineDetectionPattern = '.*--\](\s|\t)*$'

[DOUBLEDASHES_STYLE]
firstLine = '--'
endLine = "--\n"
beforeEachLine = '-- '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '--.*$'
lastLineDetectionPattern = '--.*$'

[DYNASCRIPT3_STYLE]
firstLine = "<!---\n"
endLine = "\n--->"
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*<!---.*$'
lastLineDetectionPattern = '.*--->(\s|\t)*$'

[SINGLE_LINE_DOUBLESLASH_STYLE]
firstLine = ''
endLine = ''
beforeEachLine = '// '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = '//.*$'
lastLineDetectionPattern = '//.*$'

[XML_PER_LINE]
firstLine = "\n"
endLine = "\n"
beforeEachLine = '<!-- '
afterEachLine = ' -->'
allowBlankLines = false
multipleLines = false
padLines = true
skipLinePattern = '^<\?xml.*>$'
firstLineDetectionPattern = '(\s|\t)*<!--.*$'
lastLineDetectionPattern = '.*-->(\s|\t)*$'

[UNKNOWN]
firstLine = ''
endLine = ''
beforeEachLine = ''
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
firstLineDetectionPattern = ''
lastLineDetectionPattern = ''

[JAVADOC_STYLE]
firstLine = '/**'
endLine = ' */'
beforeEachLine = ' * '
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*/\*.*$'
lastLineDetectionPattern = '.*\*/(\s|\t)*$'

[DYNASCRIPT_STYLE]
firstLine = "<%--\n"
endLine = "\n--%>"
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*<%--.*$'
lastLineDetectionPattern = '.*--%>(\s|\t)*$'

[FTL]
firstLine = "<#--\n"
endLine = "\n-->"
beforeEachLine = '    '
afterEachLine = ''
allowBlankLines = true
multipleLines = true
padLines = false
firstLineDetectionPattern = '(\s|\t)*<#--.*$'
lastLineDetectionPattern = '.*-->(\s|\t)*$'
